<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>2.2.1</AssemblyVersion>
        <FileVersion>2.2.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Blackwall.Core\Blackwall.Core.csproj" />
      <ProjectReference Include="..\Blackwall.Infrastructure\Blackwall.Infrastructure.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.Abstractions\Blackwall.Modules.Abstractions.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.Runtime\Blackwall.Modules.Runtime.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.LinkProtection\Blackwall.Modules.LinkProtection.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.DetectionMatrix\Blackwall.Modules.DetectionMatrix.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.ContentGuard\Blackwall.Modules.ContentGuard.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.Banlist\Blackwall.Modules.Banlist.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
      <PackageReference Include="TwitchLib.Api" Version="3.10.2" />
      <PackageReference Include="TwitchLib.Client" Version="4.0.1" />
    </ItemGroup>

</Project>
