<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>2.0.0</AssemblyVersion>
        <FileVersion>2.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Blackwall.Core\Blackwall.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.30.2" />
      <PackageReference Include="Grpc.Tools" Version="2.71.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
      <PackageReference Include="StackExchange.Redis" Version="3.0.7" />
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="Proto\safebrowsing_v5.proto" GrpcServices="None" />
    </ItemGroup>

</Project>
