syntax = "proto3";

option csharp_namespace = "Blackwall.LinkProtection.SafeBrowsingProto";

package safebrowsing.v5;

enum ThreatType {
  THREAT_TYPE_UNSPECIFIED = 0;
  MALWARE = 1;
  SOCIAL_ENGINEERING = 2;
  UNWANTED_SOFTWARE = 3;
  POTENTIALLY_HARMFUL_APPLICATION = 4;
}

enum LikelySafeType {
  LIKELY_SAFE_TYPE_UNSPECIFIED = 0;
  GENERAL_BROWSING = 1;
  CSD = 2;
  DOWNLOAD = 3;
}

enum ThreatAttribute {
  THREAT_ATTRIBUTE_UNSPECIFIED = 0;
  CANARY = 1;
  FRAME_ONLY = 2;
}

message Duration {
  int64 seconds = 1;
  int32 nanos = 2;
}

message SearchHashesResponse {
  repeated FullHash full_hashes = 1;
  Duration cache_duration = 2;
}

message FullHash {
  message FullHashDetail {
    ThreatType threat_type = 1;
    repeated ThreatAttribute attributes = 2;
  }

  bytes full_hash = 1;
  repeated FullHashDetail full_hash_details = 2;
}

message RiceDeltaEncoded32Bit {
  uint32 first_value = 1;
  int32 rice_parameter = 2;
  int32 entries_count = 3;
  bytes encoded_data = 4;
}

message RiceDeltaEncoded64Bit {
  uint64 first_value = 1;
  int32 rice_parameter = 2;
  int32 entries_count = 3;
  bytes encoded_data = 4;
}

message RiceDeltaEncoded128Bit {
  uint64 first_value_hi = 1;
  fixed64 first_value_lo = 2;
  int32 rice_parameter = 3;
  int32 entries_count = 4;
  bytes encoded_data = 5;
}

message RiceDeltaEncoded256Bit {
  uint64 first_value_first_part = 1;
  fixed64 first_value_second_part = 2;
  fixed64 first_value_third_part = 3;
  fixed64 first_value_fourth_part = 4;
  int32 rice_parameter = 5;
  int32 entries_count = 6;
  bytes encoded_data = 7;
}

message HashListMetadata {
  enum HashLength {
    HASH_LENGTH_UNSPECIFIED = 0;
    FOUR_BYTES = 2;
    EIGHT_BYTES = 3;
    SIXTEEN_BYTES = 4;
    THIRTY_TWO_BYTES = 5;
  }

  repeated ThreatType threat_types = 1;
  repeated LikelySafeType likely_safe_types = 2;
  string description = 4;
  HashLength hash_length = 6;
}

message HashList {
  oneof compressed_additions {
    RiceDeltaEncoded32Bit additions_four_bytes = 4;
    RiceDeltaEncoded64Bit additions_eight_bytes = 9;
    RiceDeltaEncoded128Bit additions_sixteen_bytes = 10;
    RiceDeltaEncoded256Bit additions_thirty_two_bytes = 11;
  }

  string name = 1;
  bytes version = 2;
  bool partial_update = 3;
  RiceDeltaEncoded32Bit compressed_removals = 5;
  Duration minimum_wait_duration = 6;
  bytes sha256_checksum = 7;
  HashListMetadata metadata = 8;
}

message BatchGetHashListsResponse {
  repeated HashList hash_lists = 1;
}

message ListHashListsResponse {
  repeated HashList hash_lists = 1;
  string next_page_token = 2;
}
