// <auto-generated />
using System;
using Blackwall.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blackwall.Infrastructure.Migrations
{
    [DbContext(typeof(BlackwallDbContext))]
    [Migration("20260805172433_AddTwitchRemovedManagers")]
    partial class AddTwitchRemovedManagers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blackwall.Core.Entities.AiSentinelConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("AutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDryRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTrainingMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OllamaHeader1Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OllamaHeader1Value")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OllamaHeader2Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OllamaHeader2Value")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OllamaHeader3Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OllamaHeader3Value")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OllamaUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Provider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildInstanceId")
                        .IsUnique();

                    b.ToTable("AiSentinelConfigurations");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.AiSentinelLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AiSentinelConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("DiscordMessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmbedsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("MessageTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("Reasoning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainingFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("WouldAction")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AiSentinelConfigurationId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("AiSentinelConfigurationId", "CreatedAtUtc");

                    b.ToTable("AiSentinelLogs");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActiveDisplayNameProvider")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("DiscordRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DiscordTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordUserId")
                        .HasMaxLength(32)
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("LinkAccountsWarningDismissed")
                        .HasColumnType("boolean");

                    b.Property<string>("TwitchAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("TwitchDisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TwitchProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("TwitchRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TwitchTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TwitchUserId")
                        .HasMaxLength(20)
                        .HasColumnType("bigint");

                    b.Property<string>("TwitchUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasFilter("\"DiscordUserId\" IS NOT NULL");

                    b.HasIndex("TwitchUserId")
                        .IsUnique()
                        .HasFilter("\"TwitchUserId\" IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildAllowedBot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BotUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordBotId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpamConfigurationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SpamConfigurationId", "DiscordBotId")
                        .IsUnique();

                    b.ToTable("GuildAllowedBots");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GuildInstanceId", "DiscordUserId")
                        .IsUnique();

                    b.ToTable("GuildBans");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBanSyncRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SourceDiscordGuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetGuildInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TargetGuildInstanceId", "SourceDiscordGuildId")
                        .IsUnique();

                    b.ToTable("GuildBanSyncRules");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBannedWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SpamConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SpamConfigurationId", "Word")
                        .IsUnique();

                    b.ToTable("GuildBannedWords");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBlacklist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SpamConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("SpamConfigurationId", "Url")
                        .IsUnique();

                    b.ToTable("GuildBlacklists");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBlacklistDomain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("SpamConfigurationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SpamConfigurationId", "Domain")
                        .IsUnique();

                    b.ToTable("GuildBlacklistDomains");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordGuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("IconHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ShareBanList")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiscordGuildId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("GuildInstances");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildManager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordRoleId")
                        .HasMaxLength(32)
                        .HasColumnType("bigint");

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GuildInstanceId", "UserId", "DiscordRoleId")
                        .IsUnique();

                    b.ToTable("GuildManagers");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildModuleInstallation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanPerformActions")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntryPoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GitUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleAuthor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ModuleVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildInstanceId", "ModuleName")
                        .IsUnique();

                    b.ToTable("GuildModuleInstallations");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.MessageAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarHash")
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Violations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("GuildInstanceId", "CreatedAtUtc");

                    b.ToTable("MessageAuditEvents");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.MessageAuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarHash")
                        .HasColumnType("text");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("DiscordMessageId")
                        .HasColumnType("bigint");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("EmbedsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("MessageTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("MessageAuditRecords");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.NetWatchSnareChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordChannelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<long>("SpamConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<int>("TimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpamConfigurationId", "DiscordChannelId")
                        .IsUnique();

                    b.ToTable("NetWatchSnareChannels");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.SpamConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountScoringTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("AntiRaidCooldownMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<int>("AntiRaidJoinThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("AntiRaidWindowSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<bool>("AutoTimeoutHighRiskOnJoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("AutoTimeoutMediumRiskOnJoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("BlockInviteLinks")
                        .HasColumnType("boolean");

                    b.Property<bool>("BlockSuspiciousLinks")
                        .HasColumnType("boolean");

                    b.Property<int>("ContentGuardAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("ContentGuardAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("ContentGuardCopypastaHashing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ContentGuardCopypastaMinLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(200);

                    b.Property<int>("ContentGuardCopypastaThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("ContentGuardCopypastaWindowSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<bool>("ContentGuardFuzzyMatching")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ContentGuardFuzzyThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<bool>("ContentGuardInvisibleCharScrubbing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ContentGuardMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ContentGuardTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<bool>("ContentGuardZalgoBlocking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ContentGuardZalgoMaxCombining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuplicateAction")
                        .HasColumnType("integer");

                    b.Property<bool>("DuplicateAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("DuplicateCrossChannelEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("DuplicateMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("DuplicateMessageThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("DuplicateTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("DuplicateWindowSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<int>("InviteLinkAction")
                        .HasColumnType("integer");

                    b.Property<bool>("InviteLinkAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("InviteLinkMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("InviteLinkTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<bool>("IsAccountScoringEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsAntiRaidEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsContentGuardEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDryRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLockedDown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMessageAuditEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTestMode")
                        .HasColumnType("boolean");

                    b.Property<bool>("LinkWhitelistMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long?>("LogChannelId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxMessagesPerWindow")
                        .HasColumnType("integer");

                    b.Property<int>("MentionLimit")
                        .HasColumnType("integer");

                    b.Property<int>("MentionLimitAction")
                        .HasColumnType("integer");

                    b.Property<bool>("MentionLimitAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MentionLimitMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("MentionLimitTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("MessageAuditRetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<int>("RateLimitAction")
                        .HasColumnType("integer");

                    b.Property<bool>("RateLimitAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("RateLimitMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RateLimitTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("RateLimitWindowSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("SafeBrowsingBlockUnsure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("SafeBrowsingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SuspiciousLinkAction")
                        .HasColumnType("integer");

                    b.Property<bool>("SuspiciousLinkAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SuspiciousLinkMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SuspiciousLinkTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildInstanceId")
                        .IsUnique();

                    b.ToTable("SpamConfigurations");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchAllowedBot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BotUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TwitchChannelConfigurationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TwitchChannelConfigurationId", "BotUsername")
                        .IsUnique();

                    b.ToTable("TwitchAllowedBots");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchChannelConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoAddManagers")
                        .HasColumnType("boolean");

                    b.Property<string>("CommandTrigger")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<long>("TwitchChannelInstanceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TwitchChannelInstanceId")
                        .IsUnique();

                    b.ToTable("TwitchChannelConfigurations");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchChannelInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BotAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("BotRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BotTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TwitchUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("TwitchUserId")
                        .IsUnique();

                    b.ToTable("TwitchChannelInstances");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchChannelManager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<long>("TwitchChannelInstanceId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TwitchChannelInstanceId", "UserId")
                        .IsUnique();

                    b.ToTable("TwitchChannelManagers");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchRemovedManager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TwitchChannelInstanceId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TwitchChannelInstanceId", "UserId")
                        .IsUnique();

                    b.ToTable("TwitchRemovedManagers");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.AiSentinelConfiguration", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithOne("AiSentinelConfiguration")
                        .HasForeignKey("Blackwall.Core.Entities.AiSentinelConfiguration", "GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.AiSentinelLog", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.AiSentinelConfiguration", "AiSentinelConfiguration")
                        .WithMany("Logs")
                        .HasForeignKey("AiSentinelConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiSentinelConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildAllowedBot", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.SpamConfiguration", "SpamConfiguration")
                        .WithMany("AllowedBots")
                        .HasForeignKey("SpamConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpamConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBan", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithMany("Bans")
                        .HasForeignKey("GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBanSyncRule", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "TargetGuildInstance")
                        .WithMany("BanSyncRules")
                        .HasForeignKey("TargetGuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetGuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBannedWord", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.SpamConfiguration", "SpamConfiguration")
                        .WithMany("BannedWords")
                        .HasForeignKey("SpamConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpamConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBlacklist", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.SpamConfiguration", "SpamConfiguration")
                        .WithMany("Blacklists")
                        .HasForeignKey("SpamConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpamConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBlacklistDomain", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.SpamConfiguration", "SpamConfiguration")
                        .WithMany("BlacklistDomains")
                        .HasForeignKey("SpamConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpamConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildInstance", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.AppUser", "OwnerUser")
                        .WithMany("OwnedGuilds")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildManager", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithMany("Managers")
                        .HasForeignKey("GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blackwall.Core.Entities.AppUser", "User")
                        .WithMany("ManagedGuilds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildModuleInstallation", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithMany()
                        .HasForeignKey("GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.MessageAuditEvent", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithMany()
                        .HasForeignKey("GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.MessageAuditRecord", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.MessageAuditEvent", "Event")
                        .WithMany("Records")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.NetWatchSnareChannel", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.SpamConfiguration", "SpamConfiguration")
                        .WithMany("NetWatchSnareChannels")
                        .HasForeignKey("SpamConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpamConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.SpamConfiguration", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithOne("SpamConfiguration")
                        .HasForeignKey("Blackwall.Core.Entities.SpamConfiguration", "GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchAllowedBot", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.TwitchChannelConfiguration", "TwitchChannelConfiguration")
                        .WithMany("AllowedBots")
                        .HasForeignKey("TwitchChannelConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TwitchChannelConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchChannelConfiguration", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.TwitchChannelInstance", "TwitchChannelInstance")
                        .WithOne("Configuration")
                        .HasForeignKey("Blackwall.Core.Entities.TwitchChannelConfiguration", "TwitchChannelInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TwitchChannelInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchChannelInstance", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.AppUser", "OwnerUser")
                        .WithMany("OwnedTwitchChannels")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchChannelManager", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.TwitchChannelInstance", "TwitchChannelInstance")
                        .WithMany("Managers")
                        .HasForeignKey("TwitchChannelInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blackwall.Core.Entities.AppUser", "User")
                        .WithMany("ManagedTwitchChannels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TwitchChannelInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.AiSentinelConfiguration", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.AppUser", b =>
                {
                    b.Navigation("ManagedGuilds");

                    b.Navigation("ManagedTwitchChannels");

                    b.Navigation("OwnedGuilds");

                    b.Navigation("OwnedTwitchChannels");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildInstance", b =>
                {
                    b.Navigation("AiSentinelConfiguration")
                        .IsRequired();

                    b.Navigation("BanSyncRules");

                    b.Navigation("Bans");

                    b.Navigation("Managers");

                    b.Navigation("SpamConfiguration")
                        .IsRequired();
                });

            modelBuilder.Entity("Blackwall.Core.Entities.MessageAuditEvent", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.SpamConfiguration", b =>
                {
                    b.Navigation("AllowedBots");

                    b.Navigation("BannedWords");

                    b.Navigation("BlacklistDomains");

                    b.Navigation("Blacklists");

                    b.Navigation("NetWatchSnareChannels");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchChannelConfiguration", b =>
                {
                    b.Navigation("AllowedBots");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.TwitchChannelInstance", b =>
                {
                    b.Navigation("Configuration");

                    b.Navigation("Managers");
                });
#pragma warning restore 612, 618
        }
    }
}
