// <auto-generated />
using System;
using Blackwall.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blackwall.Infrastructure.Migrations
{
    [DbContext(typeof(BlackwallDbContext))]
    partial class BlackwallDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blackwall.Core.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("DiscordRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DiscordTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordUserId")
                        .HasMaxLength(32)
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordGuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("IconHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiscordGuildId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("GuildInstances");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildManager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordRoleId")
                        .HasMaxLength(32)
                        .HasColumnType("bigint");

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GuildInstanceId", "UserId", "DiscordRoleId")
                        .IsUnique();

                    b.ToTable("GuildManagers");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.SpamConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("BlockInviteLinks")
                        .HasColumnType("boolean");

                    b.Property<bool>("BlockSuspiciousLinks")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuplicateMessageThreshold")
                        .HasColumnType("integer");

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDryRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long?>("LogChannelId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxMessagesPerWindow")
                        .HasColumnType("integer");

                    b.Property<int>("MentionLimit")
                        .HasColumnType("integer");

                    b.Property<int>("MessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RateLimitWindowSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildInstanceId")
                        .IsUnique();

                    b.ToTable("SpamConfigurations");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildInstance", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.AppUser", "OwnerUser")
                        .WithMany("OwnedGuilds")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildManager", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithMany("Managers")
                        .HasForeignKey("GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blackwall.Core.Entities.AppUser", "User")
                        .WithMany("ManagedGuilds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.SpamConfiguration", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithOne("SpamConfiguration")
                        .HasForeignKey("Blackwall.Core.Entities.SpamConfiguration", "GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.AppUser", b =>
                {
                    b.Navigation("ManagedGuilds");

                    b.Navigation("OwnedGuilds");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildInstance", b =>
                {
                    b.Navigation("Managers");

                    b.Navigation("SpamConfiguration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
