// <auto-generated />
using System;
using Blackwall.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blackwall.Infrastructure.Migrations
{
    [DbContext(typeof(BlackwallDbContext))]
    partial class BlackwallDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blackwall.Core.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("DiscordRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DiscordTokenExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordUserId")
                        .HasMaxLength(32)
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GuildInstanceId", "DiscordUserId")
                        .IsUnique();

                    b.ToTable("GuildBans");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBanSyncRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SourceDiscordGuildId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetGuildInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TargetGuildInstanceId", "SourceDiscordGuildId")
                        .IsUnique();

                    b.ToTable("GuildBanSyncRules");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBannedWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SpamConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SpamConfigurationId", "Word")
                        .IsUnique();

                    b.ToTable("GuildBannedWords");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBlacklist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SpamConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("SpamConfigurationId", "Url")
                        .IsUnique();

                    b.ToTable("GuildBlacklists");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBlacklistDomain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("SpamConfigurationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SpamConfigurationId", "Domain")
                        .IsUnique();

                    b.ToTable("GuildBlacklistDomains");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordGuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("IconHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("OwnerUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ShareBanList")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiscordGuildId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("GuildInstances");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildManager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordRoleId")
                        .HasMaxLength(32)
                        .HasColumnType("bigint");

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("GuildInstanceId", "UserId", "DiscordRoleId")
                        .IsUnique();

                    b.ToTable("GuildManagers");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.SpamConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountScoringTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("AntiRaidCooldownMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<int>("AntiRaidJoinThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("AntiRaidWindowSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<bool>("AutoTimeoutHighRiskOnJoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("AutoTimeoutMediumRiskOnJoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("BlockInviteLinks")
                        .HasColumnType("boolean");

                    b.Property<bool>("BlockSuspiciousLinks")
                        .HasColumnType("boolean");

                    b.Property<int>("ContentGuardAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("ContentGuardAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("ContentGuardCopypastaHashing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ContentGuardCopypastaMinLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(200);

                    b.Property<int>("ContentGuardCopypastaThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("ContentGuardCopypastaWindowSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<bool>("ContentGuardFuzzyMatching")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ContentGuardFuzzyThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<bool>("ContentGuardInvisibleCharScrubbing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ContentGuardMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ContentGuardTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<bool>("ContentGuardZalgoBlocking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ContentGuardZalgoMaxCombining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuplicateAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("DuplicateAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("DuplicateCrossChannelEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("DuplicateMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("DuplicateMessageThreshold")
                        .HasColumnType("integer");

                    b.Property<int>("DuplicateTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("DuplicateWindowSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<long>("GuildInstanceId")
                        .HasColumnType("bigint");

                    b.Property<int>("InviteLinkAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("InviteLinkAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("InviteLinkMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("InviteLinkTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<bool>("IsAccountScoringEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsAntiRaidEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsContentGuardEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDryRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLockedDown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LinkWhitelistMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long?>("LogChannelId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxMessagesPerWindow")
                        .HasColumnType("integer");

                    b.Property<int>("MentionLimit")
                        .HasColumnType("integer");

                    b.Property<int>("MentionLimitAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("MentionLimitAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MentionLimitMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("MentionLimitTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("RateLimitAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("RateLimitAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("RateLimitMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RateLimitTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("RateLimitWindowSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("SafeBrowsingBlockUnsure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("SafeBrowsingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SuspiciousLinkAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("SuspiciousLinkAutoLockdown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SuspiciousLinkMessageDeleteDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("SuspiciousLinkTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildInstanceId")
                        .IsUnique();

                    b.ToTable("SpamConfigurations");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBan", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithMany("Bans")
                        .HasForeignKey("GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBanSyncRule", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "TargetGuildInstance")
                        .WithMany("BanSyncRules")
                        .HasForeignKey("TargetGuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetGuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBannedWord", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.SpamConfiguration", "SpamConfiguration")
                        .WithMany("BannedWords")
                        .HasForeignKey("SpamConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpamConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBlacklist", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.SpamConfiguration", "SpamConfiguration")
                        .WithMany("Blacklists")
                        .HasForeignKey("SpamConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpamConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildBlacklistDomain", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.SpamConfiguration", "SpamConfiguration")
                        .WithMany("BlacklistDomains")
                        .HasForeignKey("SpamConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpamConfiguration");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildInstance", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.AppUser", "OwnerUser")
                        .WithMany("OwnedGuilds")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildManager", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithMany("Managers")
                        .HasForeignKey("GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blackwall.Core.Entities.AppUser", "User")
                        .WithMany("ManagedGuilds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.SpamConfiguration", b =>
                {
                    b.HasOne("Blackwall.Core.Entities.GuildInstance", "GuildInstance")
                        .WithOne("SpamConfiguration")
                        .HasForeignKey("Blackwall.Core.Entities.SpamConfiguration", "GuildInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildInstance");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.AppUser", b =>
                {
                    b.Navigation("ManagedGuilds");

                    b.Navigation("OwnedGuilds");
                });

            modelBuilder.Entity("Blackwall.Core.Entities.GuildInstance", b =>
                {
                    b.Navigation("BanSyncRules");

                    b.Navigation("Bans");

                    b.Navigation("Managers");

                    b.Navigation("SpamConfiguration")
                        .IsRequired();
                });

            modelBuilder.Entity("Blackwall.Core.Entities.SpamConfiguration", b =>
                {
                    b.Navigation("BannedWords");

                    b.Navigation("BlacklistDomains");

                    b.Navigation("Blacklists");
                });
#pragma warning restore 612, 618
        }
    }
}
