<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <AssemblyVersion>1.0.0-rc.1</AssemblyVersion>
        <FileVersion>1.0.0-rc.1</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Blackwall.Core\Blackwall.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNetEnv" Version="3.2.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    </ItemGroup>

</Project>
