<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
        <AssemblyVersion>2.2.0</AssemblyVersion>
        <FileVersion>2.2.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Blackwall.Core\Blackwall.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="DotNetEnv" Version="3.2.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    </ItemGroup>

</Project>
