<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Blackwall.Bot.Discord\Blackwall.Bot.Discord.csproj" />
      <ProjectReference Include="..\Blackwall.Bot.Twitch\Blackwall.Bot.Twitch.csproj" />
      <ProjectReference Include="..\Blackwall.Core\Blackwall.Core.csproj" />
      <ProjectReference Include="..\Blackwall.Infrastructure\Blackwall.Infrastructure.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.Runtime\Blackwall.Modules.Runtime.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.LinkProtection\Blackwall.Modules.LinkProtection.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.DetectionMatrix\Blackwall.Modules.DetectionMatrix.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.ContentGuard\Blackwall.Modules.ContentGuard.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.Banlist\Blackwall.Modules.Banlist.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Discord.Net.WebSocket" Version="3.20.1" />
      <PackageReference Include="DotNetEnv" Version="3.2.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.OpenApi" Version="2.9.0" />
      <PackageReference Include="Scalar.AspNetCore" Version="2.16.6" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
    </ItemGroup>

</Project>
