<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Blackwall.Core\Blackwall.Core.csproj" />
      <ProjectReference Include="..\Blackwall.Infrastructure\Blackwall.Infrastructure.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.Abstractions\Blackwall.Modules.Abstractions.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.LinkProtection\Blackwall.Modules.LinkProtection.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.DetectionMatrix\Blackwall.Modules.DetectionMatrix.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.ContentGuard\Blackwall.Modules.ContentGuard.csproj" />
      <ProjectReference Include="..\Blackwall.Modules.Banlist\Blackwall.Modules.Banlist.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Discord.Net" Version="3.20.1" />
      <PackageReference Include="Discord.Net.WebSocket" Version="3.20.1" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.9" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
      <PackageReference Include="StackExchange.Redis" Version="3.0.7" />
    </ItemGroup>

</Project>
